/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from depend_Release_CSR101x_A05/app_gatt_db.db_
 */

#include "depend_Release_CSR101x_A05/app_gatt_db.h"

/* GATT database */
uint16 gattDatabase[] = {
    /* 0001: Primary Service 1800 */
    0x0002, 0x0018,
    /* 0002: Characteristic Declaration 2a00 */
    0x3005, 0x0a03, 0x0000, 0x2a00,
    /* 0003: . */
    0xd501, 0x0000,
    /* 0004: Characteristic Declaration 2a01 */
    0x3005, 0x0205, 0x0001, 0x2a00,
    /* 0005: @. */
    0xd002, 0x4003,
    /* 0006: Characteristic Declaration 2a04 */
    0x3005, 0x0207, 0x0004, 0x2a00,
    /* 0007:  . ...X. */
    0xd008, 0x2003, 0x2003, 0x0000, 0x5802,
    /* 0008: Primary Service 1801 */
    0x0002, 0x0118,
    /* 0009: Primary Service 180d */
    0x0002, 0x0d18,
    /* 000a: Characteristic Declaration 2a37 */
    0x3005, 0x100b, 0x0037, 0x2a00,
    /* 000b: ................. */
    0xd411, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    /* 000c: Client Characteristic Configuration */
    0x6400,
    /* 000d: Characteristic Declaration 2a38 */
    0x3005, 0x020e, 0x0038, 0x2a00,
    /* 000e: . */
    0xd001, 0x0100,
    /* 000f: Characteristic Declaration 2a39 */
    0x3005, 0x0810, 0x0039, 0x2a00,
    /* 0010: . */
    0xd401, 0x0000,
    /* 0011: Characteristic Declaration 5f55aef5-09d6-48a5-b44b-e41d7df55743 */
    0x3013, 0x0a12, 0x0043, 0x57f5, 0x7d1d, 0xe44b, 0xb4a5, 0x48d6, 0x09f5, 0xae55, 0x5f00,
    /* 0012: . */
    0xc401, 0x0000,
    /* 0013: Primary Service 180f */
    0x0002, 0x0f18,
    /* 0014: Characteristic Declaration 2a19 */
    0x3005, 0x1215, 0x0019, 0x2a00,
    /* 0015: . */
    0xd401, 0x0000,
    /* 0016: Client Characteristic Configuration */
    0x6400,
    /* 0017: Primary Service 180a */
    0x0002, 0x0a18,
    /* 0018: Characteristic Declaration 2a25 */
    0x3005, 0x0219, 0x0025, 0x2a00,
    /* 0019: 0000-0000-0000-0001 */
    0xd013, 0x3030, 0x3030, 0x2d30, 0x3030, 0x302d, 0x3030, 0x3030, 0x2d30, 0x3030, 0x3100,
    /* 001a: Characteristic Declaration 2a27 */
    0x3005, 0x021b, 0x0027, 0x2a00,
    /* 001b: Blah */
    0xd004, 0x426c, 0x6168,
    /* 001c: Characteristic Declaration 2a26 */
    0x3005, 0x021d, 0x0026, 0x2a00,
    /* 001d: v0.0.0.0.0.0.1 */
    0xd00e, 0x7630, 0x2e30, 0x2e30, 0x2e30, 0x2e30, 0x2e30, 0x2e31,
    /* 001e: Characteristic Declaration 2a28 */
    0x3005, 0x021f, 0x0028, 0x2a00,
    /* 001f: v0.0.0.0.0.0.1 */
    0xd00e, 0x7630, 0x2e30, 0x2e30, 0x2e30, 0x2e30, 0x2e30, 0x2e31,
    /* 0020: Characteristic Declaration 2a29 */
    0x3005, 0x0221, 0x0029, 0x2a00,
    /* 0021: Heekari */
    0xd007, 0x4865, 0x656b, 0x6172, 0x6900,
    /* 0022: Characteristic Declaration 2a50 */
    0x3005, 0x0223, 0x0050, 0x2a00,
    /* 0023: ...L... */
    0xd007, 0x010a, 0x004c, 0x0100, 0x0100,
};

uint16 *GattGetDatabase(uint16 *len)
{
    *len = sizeof(gattDatabase);
    return gattDatabase;
}

/* End-of-File */
